import type { LookupOption } from './lookups.data';

function city(value: string, label: string, labelAr: string): LookupOption {
  return { value, label, labelAr };
}

/** Major cities keyed by ISO country code */
export const CITIES_BY_COUNTRY: Record<string, LookupOption[]> = {
  SA: [
    city('Riyadh', 'Riyadh', 'الرياض'),
    city('Jeddah', 'Jeddah', 'جدة'),
    city('Mecca', 'Mecca', 'مكة المكرمة'),
    city('Medina', 'Medina', 'المدينة المنورة'),
    city('Dammam', 'Dammam', 'الدمام'),
    city('Khobar', 'Khobar', 'الخبر'),
    city('Dhahran', 'Dhahran', 'الظهران'),
    city('Taif', 'Taif', 'الطائف'),
    city('Abha', 'Abha', 'أبها'),
    city('Tabuk', 'Tabuk', 'تبوك'),
    city('Buraidah', 'Buraidah', 'بريدة'),
    city('Khamis Mushait', 'Khamis Mushait', 'خميس مشيط'),
    city('Najran', 'Najran', 'نجران'),
    city('Jazan', 'Jazan', 'جازان'),
    city('Hail', 'Hail', 'حائل'),
  ],
  AE: [
    city('Dubai', 'Dubai', 'دبي'),
    city('Abu Dhabi', 'Abu Dhabi', 'أبوظبي'),
    city('Sharjah', 'Sharjah', 'الشارقة'),
    city('Ajman', 'Ajman', 'عجمان'),
    city('Ras Al Khaimah', 'Ras Al Khaimah', 'رأس الخيمة'),
    city('Fujairah', 'Fujairah', 'الفجيرة'),
    city('Al Ain', 'Al Ain', 'العين'),
  ],
  KW: [
    city('Kuwait City', 'Kuwait City', 'مدينة الكويت'),
    city('Hawalli', 'Hawalli', 'حولي'),
    city('Salmiya', 'Salmiya', 'السالمية'),
    city('Farwaniya', 'Farwaniya', 'الفروانية'),
    city('Jahra', 'Jahra', 'الجهراء'),
    city('Ahmadi', 'Ahmadi', 'الأحمدي'),
  ],
  QA: [
    city('Doha', 'Doha', 'الدوحة'),
    city('Al Rayyan', 'Al Rayyan', 'الريان'),
    city('Al Wakrah', 'Al Wakrah', 'الوكرة'),
    city('Umm Salal', 'Umm Salal', 'أم صلال'),
    city('Al Khor', 'Al Khor', 'الخور'),
  ],
  BH: [
    city('Manama', 'Manama', 'المنامة'),
    city('Riffa', 'Riffa', 'الرفاع'),
    city('Muharraq', 'Muharraq', 'المحرق'),
    city('Isa Town', 'Isa Town', 'مدينة عيسى'),
    city('Sitra', 'Sitra', 'سترة'),
  ],
  OM: [
    city('Muscat', 'Muscat', 'مسقط'),
    city('Salalah', 'Salalah', 'صلالة'),
    city('Sohar', 'Sohar', 'صحار'),
    city('Nizwa', 'Nizwa', 'نزوى'),
    city('Sur', 'Sur', 'صور'),
  ],
  IQ: [
    city('Baghdad', 'Baghdad', 'بغداد'),
    city('Basra', 'Basra', 'البصرة'),
    city('Erbil', 'Erbil', 'أربيل'),
    city('Mosul', 'Mosul', 'الموصل'),
    city('Najaf', 'Najaf', 'النجف'),
    city('Karbala', 'Karbala', 'كربلاء'),
    city('Sulaymaniyah', 'Sulaymaniyah', 'السليمانية'),
    city('Kirkuk', 'Kirkuk', 'كركوك'),
    city('Nasiriyah', 'Nasiriyah', 'الناصرية'),
    city('Hillah', 'Hillah', 'الحلة'),
  ],
  JO: [
    city('Amman', 'Amman', 'عمّان'),
    city('Zarqa', 'Zarqa', 'الزرقاء'),
    city('Irbid', 'Irbid', 'إربد'),
    city('Aqaba', 'Aqaba', 'العقبة'),
    city('Madaba', 'Madaba', 'مادبا'),
  ],
  EG: [
    city('Cairo', 'Cairo', 'القاهرة'),
    city('Alexandria', 'Alexandria', 'الإسكندرية'),
    city('Giza', 'Giza', 'الجيزة'),
    city('Sharm El Sheikh', 'Sharm El Sheikh', 'شرم الشيخ'),
    city('Luxor', 'Luxor', 'الأقصر'),
    city('Aswan', 'Aswan', 'أسوان'),
    city('Port Said', 'Port Said', 'بورسعيد'),
    city('Mansoura', 'Mansoura', 'المنصورة'),
  ],
  PS: [
    city('Jerusalem', 'Jerusalem', 'القدس'),
    city('Ramallah', 'Ramallah', 'رام الله'),
    city('Gaza', 'Gaza', 'غزة'),
    city('Nablus', 'Nablus', 'نابلس'),
    city('Hebron', 'Hebron', 'الخليل'),
    city('Bethlehem', 'Bethlehem', 'بيت لحم'),
  ],
  LB: [
    city('Beirut', 'Beirut', 'بيروت'),
    city('Tripoli', 'Tripoli', 'طرابلس'),
    city('Sidon', 'Sidon', 'صيدا'),
    city('Tyre', 'Tyre', 'صور'),
    city('Zahle', 'Zahle', 'زحلة'),
  ],
  SY: [
    city('Damascus', 'Damascus', 'دمشق'),
    city('Aleppo', 'Aleppo', 'حلب'),
    city('Homs', 'Homs', 'حمص'),
    city('Latakia', 'Latakia', 'اللاذقية'),
    city('Hama', 'Hama', 'حماة'),
  ],
  YE: [
    city('Sanaa', 'Sanaa', 'صنعاء'),
    city('Aden', 'Aden', 'عدن'),
    city('Taiz', 'Taiz', 'تعز'),
    city('Hodeidah', 'Hodeidah', 'الحديدة'),
  ],
  SD: [
    city('Khartoum', 'Khartoum', 'الخرطوم'),
    city('Omdurman', 'Omdurman', 'أم درمان'),
    city('Port Sudan', 'Port Sudan', 'بورتسودان'),
  ],
  MA: [
    city('Casablanca', 'Casablanca', 'الدار البيضاء'),
    city('Rabat', 'Rabat', 'الرباط'),
    city('Marrakesh', 'Marrakesh', 'مراكش'),
    city('Fes', 'Fes', 'فاس'),
    city('Tangier', 'Tangier', 'طنجة'),
  ],
  TN: [
    city('Tunis', 'Tunis', 'تونس'),
    city('Sfax', 'Sfax', 'صفاقس'),
    city('Sousse', 'Sousse', 'سوسة'),
  ],
  DZ: [
    city('Algiers', 'Algiers', 'الجزائر'),
    city('Oran', 'Oran', 'وهران'),
    city('Constantine', 'Constantine', 'قسنطينة'),
  ],
  LY: [
    city('Tripoli', 'Tripoli', 'طرابلس'),
    city('Benghazi', 'Benghazi', 'بنغازي'),
    city('Misrata', 'Misrata', 'مصراتة'),
  ],
  TR: [
    city('Istanbul', 'Istanbul', 'إسطنبول'),
    city('Ankara', 'Ankara', 'أنقرة'),
    city('Izmir', 'Izmir', 'إزمير'),
    city('Antalya', 'Antalya', 'أنطاليا'),
  ],
  US: [
    city('New York', 'New York', 'نيويورك'),
    city('Los Angeles', 'Los Angeles', 'لوس أنجلوس'),
    city('Chicago', 'Chicago', 'شيكاغو'),
    city('Houston', 'Houston', 'هيوستن'),
    city('Washington', 'Washington', 'واشنطن'),
  ],
  GB: [
    city('London', 'London', 'لندن'),
    city('Manchester', 'Manchester', 'مانشستر'),
    city('Birmingham', 'Birmingham', 'برمنغهام'),
    city('Edinburgh', 'Edinburgh', 'إدنبرة'),
  ],
  DE: [
    city('Berlin', 'Berlin', 'برلين'),
    city('Munich', 'Munich', 'ميونخ'),
    city('Hamburg', 'Hamburg', 'هامبورغ'),
    city('Frankfurt', 'Frankfurt', 'فرانكفورت'),
  ],
  FR: [
    city('Paris', 'Paris', 'باريس'),
    city('Lyon', 'Lyon', 'ليون'),
    city('Marseille', 'Marseille', 'مرسيليا'),
  ],
  IN: [
    city('Mumbai', 'Mumbai', 'مومباي'),
    city('Delhi', 'Delhi', 'دلهي'),
    city('Bangalore', 'Bangalore', 'بنغالور'),
    city('Hyderabad', 'Hyderabad', 'حيدر آباد'),
  ],
  CN: [
    city('Beijing', 'Beijing', 'بكين'),
    city('Shanghai', 'Shanghai', 'شنغهاي'),
    city('Guangzhou', 'Guangzhou', 'غوانغجو'),
    city('Shenzhen', 'Shenzhen', 'شنتشن'),
  ],
  PK: [
    city('Karachi', 'Karachi', 'كراتشي'),
    city('Lahore', 'Lahore', 'لاهور'),
    city('Islamabad', 'Islamabad', 'إسلام آباد'),
  ],
};

export const LOOKUP_CITY_DEFAULTS: Record<string, string> = {
  SA: 'Riyadh',
  AE: 'Dubai',
  KW: 'Kuwait City',
  QA: 'Doha',
  BH: 'Manama',
  OM: 'Muscat',
  IQ: 'Baghdad',
  JO: 'Amman',
  EG: 'Cairo',
  PS: 'Ramallah',
  LB: 'Beirut',
  SY: 'Damascus',
  YE: 'Sanaa',
  SD: 'Khartoum',
  MA: 'Casablanca',
  TN: 'Tunis',
  DZ: 'Algiers',
  LY: 'Tripoli',
  TR: 'Istanbul',
  US: 'New York',
  GB: 'London',
  DE: 'Berlin',
  FR: 'Paris',
  IN: 'Mumbai',
  CN: 'Beijing',
  PK: 'Karachi',
};
